# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ranking.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'ranking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rranking.proto\x12\x07ranking\"\x07\n\x05\x45mpty\"\x17\n\x04Pong\x12\x0f\n\x07message\x18\x01 \x01(\t\";\n\x15SampleRankingResponse\x12\"\n\x05items\x18\x01 \x03(\x0b\x32\x13.ranking.RankedItem\")\n\nRankedItem\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0c\n\x04rank\x18\x02 \x01(\x05\x32{\n\x0eRankingService\x12%\n\x04Ping\x12\x0e.ranking.Empty\x1a\r.ranking.Pong\x12\x42\n\x10GetSampleRanking\x12\x0e.ranking.Empty\x1a\x1e.ranking.SampleRankingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ranking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=26
  _globals['_EMPTY']._serialized_end=33
  _globals['_PONG']._serialized_start=35
  _globals['_PONG']._serialized_end=58
  _globals['_SAMPLERANKINGRESPONSE']._serialized_start=60
  _globals['_SAMPLERANKINGRESPONSE']._serialized_end=119
  _globals['_RANKEDITEM']._serialized_start=121
  _globals['_RANKEDITEM']._serialized_end=162
  _globals['_RANKINGSERVICE']._serialized_start=164
  _globals['_RANKINGSERVICE']._serialized_end=287
# @@protoc_insertion_point(module_scope)
